### ISSUE TITLE
When docker is closed

### ISSUE THREAD

**Issue by staugur** [staugur/Sdp#18]
Traceback (most recent call last):
  File "./sdp.py", line 41, in <module>
    SdpCloudRun(*_user)
  File "./sdp.py", line 25, in SdpCloudRun
    StartAll('WEB', *_user)
  File "/home/taochengwei/sdp/Core/Handler.py", line 71, in StartAll
    cid = D.Create(mode='bridge')    #docker network mode='bridge' or 'host'(not allow none and ContainerID)
  File "/home/taochengwei/sdp/Core/Docker.py", line 66, in Create
    if not self.Images():
  File "/home/taochengwei/sdp/Core/Docker.py", line 25, in Images
    return self.connect.images(self.image)
  File "/usr/lib/python2.6/site-packages/docker/client.py", line 403, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
  File "/usr/lib/python2.6/site-packages/docker/clientbase.py", line 87, in _get
    return self.get(url, *_self._set_request_timeout(kwargs))
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/adapters.py", line 412, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))

**Comment by staugur** [comment]
这是docker抛出的错误，原因是docker服务关闭了，只要开启就好了。
